# Generated by Django 5.1.7 on 2025-04-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('ranking', models.IntegerField()),
                ('cut_off', models.FloatField()),
                ('domain', models.CharField(max_length=255)),
                ('seats_available', models.IntegerField()),
            ],
        ),
    ]
